version: '3'

volumes:
  ghost_data:
  mysql_data:
  certs_volume:
  nginx_logs:

services:
  ghost:
    image: ${SERVICE_GHOST_IMAGE}
    volumes:
      - ghost_data:/var/lib/ghost
    ports:
      - 2368:2368
    depends_on:
      - mysql
    environment:
      - NODE_ENV=production
    env_file:
      - ghost/.env
    restart: on-failure

  mysql:
    image: ${SERVICE_MYSQL_IMAGE}
    volumes:
      - mysql_data:/var/lib/mysql
    env_file:
      - mysql/.env
    restart: on-failure

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - certs_volume:/etc/certs
      - nginx_logs:/etc/nginx/logs
    env_file:
      - nginx/.env
    depends_on:
      - ghost
    restart: unless-stopped
