version: '3'

volumes:
  ghost_data_site_1:
  ghost_data_site_2:
  mysql_data:
  certs_volume:
  nginx_logs:

services:
  ghost_site_1: &ghost
    image: ${SERVICE_GHOST_IMAGE}
    volumes:
      - ghost_data_site_1:/var/lib/ghost
    depends_on:
      - mysql
    env_file:
      - ghost_site_1/.env
    restart: unless-stopped

  ghost_site_2:
    <<: *ghost
    volumes:
      - ghost_data_site_2:/var/lib/ghost
    env_file:
      - ghost_site_2/.env
    restart: unless-stopped

  mysql:
    image: ${SERVICE_MYSQL_IMAGE}
    volumes:
      - mysql_data:/var/lib/mysql
    env_file:
      - mysql/.env
    restart: unless-stopped

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "81:81"
      - "443:443"
    volumes:
      - certs_volume:/etc/certs
      - nginx_logs:/etc/nginx/logs
    env_file:
      - nginx/.env
    depends_on:
      - ghost_site_1
      - ghost_site_2
    restart: unless-stopped
